Repository vudor/haruJs, pull requests merged in 2021-02, with the labels that each got.

#5 improved iteration over endpoints in KoaService
  src/index.ts
  src/mappings/Mappings.ts
  src/requests/Endpoints.ts
  src/requests/Get.ts
  src/requests/MappingUtils.ts
  src/requests/Post.ts
  src/requests/RequestType.ts
  src/service/KoaService.spec.ts
  src/service/KoaService.ts
Labels: enhancement

#6 Issue#4: added jest configuration to specify the folder of executable tests
  jest.config.js
Labels: bug

#20 added a new `Newable` type since `NewableFunction` wasn't really newable
  src/core/Application.ts
  src/data/ApplicationCache.ts
  src/types.ts
Labels: bug, enhancement
